### ISSUE TITLE
0.6.x 重構

### ISSUE THREAD

**Issue by FlandreDaisuki** [FlandreDaisuki/dmhy-subscribe#17]
# CLI
## add
- [x] 訂閱用字串 / Subscribable String
- [x] 訂閱設定檔 (~ini~ yaml ~JSON~)
  ```yaml
  # 以 yaml 列出基本項

  # 顯示用標題，同時會被加入 search
  # 必須有值
  title: 搖曳露營

  # 符合關鍵字的 Thread 才會被加入 search
  # 字串陣列
  keywords:
    - 喵萌
    - 繁體

  # 符合黑名單關鍵字的 Thread 在 search 後會直接被捨棄
  # 字串陣列
  unkeywords:
    - 合集

  # 使用 JS RegExp 寫法，`\`不用寫成`\\`，以第一個 group 來 parse
  episodeParser: /第\s*(\d+(?:-\d+)?)\s*[話话]/

  # 使用 JS RegExp 寫法
  # 若 episodeParser 被定義，忽略此項
  # 但這邊是過濾切開後的 tokens，一般使用者不會看到 tokens 被如何切開...
  userBlacklistPatterns:
    - /\d+月\d+日/
    - /\d+\s*月新番/
  ```
- [x] 設定檔作為 `Subscription` 的 initial 項，再從 `~/.dmhy-subscribe/db.json` 拉已存的 threads
### 使用例
```sh
$ dmhy add "搖曳露營,萌喵,繁體"
$ dmhy add "./camp.yml"
$ dmhy add "./yorimoi.yml" "搖曳露營,萌喵,繁體"
$ dmhy add --interactive
```
## remove | rm
- [x] 沒意外的話不變
### 使用例
```sh
$ dmhy rm SID [SID ...]
$ dmhy rm --all
```
## list | ls
- [x] 隨便，想印什麼再加就好
### 使用例
```sh
$ dmhy ls # 全域資訊
$ dmhy ls SID [SID ...] # 訂閱資訊
$ dmhy ls -ss # 全部可訂閱字串
$ dmhy ls -sy # 全部訂閱設定檔
```
## download | dl
- [x] 下載用的字串(THID)目前堪用，保留？
  - ~~若為兩季以上的番，有些字幕組會先放出前半合集，這時下載單集會總是下載到該合集~~
    用 unkeywords 解決
```sh
$ dmhy dl THID [THID ...]
```
## search | find
- [x] 原功能
- [ ] 擴充替代網站？(#13) 
  - 內容不同步問題，timeout? priority?
## update
~~- [ ] 保留？~~
- [x] 使用 `dmhy --no-dl` 取代
## config | cfg
- [x] downloader
- [x] destination
- [x] aria2-jsonrpc
- [x] webhook-url
~~- [ ] 推播選項(Scheduling 應該很實用)~~ 之後開成 enhancement issue

# 其他
- [x] 爬 npm 有更新顯示更新訊息
  - 爬很慢而且爬玩才會開始主程式，目前寫死執行 15 次爬一次
- [x] 測試 Orz
- [x] 用 [yargs/yargs](https://github.com/yargs/yargs) 改寫
- [ ] 破壞性更新直接放生(?)
  - 不然現在的 rolling update 很難寫w
- [x] 命名統一
  - downloader ~client~

# d208665 之後 
## [maple3142 建議&回報](https://github.com/FlandreDaisuki/dmhy-subscribe/issues/17#issuecomment-379429240)
- [x] ~~rm --all 問題 (need more info)~~
- [x] ~~regex 錯誤會造成 crash (bug)~~
- [ ] add 整合 search (enhancement)
- [x] ~~add no argument message (enhancement)~~
- [ ] downloader 錯誤直接 throw (enhancement)
- [x] ~~不存在的指令顯示 help (enhancement)~~
- [ ] 修改已存在訂閱 (enhancement)

**Comment by maple3142** [comment]
cli 我推薦用 yargs，蠻強大的

設定檔我覺得 yaml 可能更好，比 json 更適合人類讀
```yaml
title: 搖曳露營
keywords:
  - DHR
  - 繁體
  - 720
  - Yuru
episodeParser: 
```

**Comment by FlandreDaisuki** [comment]
剛剛看了一下 `yargs` 居然自帶 locales 了
我就是覺得 tj/commander.js 一半中文一半英文很刺眼才想換掉的w
- - -
我也覺得 yaml 不錯，只是之前沒玩過不知道會不會遇到什麼雷 (奇怪的字元之類的，`\r?\n`之類的)

**Comment by maple3142** [comment]
目前發現的幾個問題和建議:

1. `rm --all` 顯示的訊息怪怪的
![rm message error](https://i.imgur.com/XiasfbL.png)

2. `add -i` 的自訂義介面可以考慮整合 `search` 指令，在輸入完標題、關鍵字、黑名單關鍵字之後會先搜尋，然後顯示列表與詢問是否要修改

3. 下面這個 yaml 會直接讓程式掛掉，看了一下應該是 https://github.com/FlandreDaisuki/dmhy-subscribe/blob/d208665d1a2acf1162b2f624a3732b898c14e043/src/dmhy/thread.js#L24 的問題
可能加個 try-catch 然後說是使用者的 regex 有問題之類的，然後 print 出有問題的那個標題
```yaml
# 以 yaml 列出基本項

# 顯示用標題，同時會被加入 search
# 必須有值
title: 搖曳露營

# 符合關鍵字的 Thread 才會被加入 search
# 字串陣列
keywords:
  - 喵萌
  - 繁體

# 符合黑名單關鍵字的 Thread 在 search 後會直接被捨棄
# 字串陣列
unkeywords:
  - 合集

# 使用 JS RegExp 寫法，`\`不用寫成`\\`，以第一個 group 來 parse
episodeParser: /第\s*(\d+(?:-\d+)?)\s*[話话]/

# 使用 JS RegExp 寫法
# 若 episodeParser 被定義，忽略此項
# 但這邊是過濾切開後的 tokens，一般使用者不會看到 tokens 被如何切開...
userBlacklistPatterns:
  - /\d+月\d+日/
  - /\d+\s*月新番/
```

4. ![add default msg](https://i.imgur.com/vuXVSfO.png)
這邊我覺得應該預設顯示 `CMD_ADD_USAGE` 的訊息更好

5. `config downloader xxx` 的時候遇到不支援為什麼不直接 error? 這應該沒有 `destination` 的問題吧

6. `config` 在發現多餘的值的時候(像是 client,webhook) 應該可以把它刪除吧，或是在 `postinstall` 完成

7. 在出現不存在的指令時顯示 help ? 例如: `dmhy test`
